// English catalogue — the source strings, and the fallback for any key another
// language has not filled in yet.
//
// Flat dotted keys, namespaced by the surface they belong to. A value is either
// a string or an object of plural forms (see i18n.svelte.js). Placeholders are
// {name}. Unit symbols are never in here: °C, W, MHz, GB and MB/s stay Latin in
// every language.
export default {
  "alert.cpuTemp": "CPU temperature {value} °C — limit is {limit} °C",
  "alert.disk": "Drive {name} is {value}% full — limit is {limit}%",
  "alert.gpuTemp": "GPU temperature {value} °C — limit is {limit} °C",
  "alert.ram": "RAM usage {value}% — limit is {limit}%",
  "app.alert.dismiss": "Dismiss",
  "app.alert.label": "Alert",
  "app.gate.afterLink": "— an open-source kernel driver installed once, system-wide. The app cannot start without it. Installation runs through winget from the official package; nothing is downloaded by the app itself.",
  "app.gate.beforeLink": "Open Monitoring reads hardware sensors through",
  "app.gate.check": "Check again",
  "app.gate.checking": "Checking…",
  "app.gate.install": "Install PawnIO",
  "app.gate.installing": "Installing…",
  "app.gate.subtitle": "driver required",
  "app.hotkey.listening": "press keys…",
  "app.hotkey.taken": "held by another application",
  "app.hud.clickThrough": "Click-through: the mouse passes into the game",
  "app.hud.enter": "Switch to overlay",
  "app.hud.exit": "Back to dashboard",
  "app.hudAlert.advice": "In the game's video settings choose",
  "app.hudAlert.borderless": "Borderless fullscreen",
  "app.hudAlert.borderlessNote": "The HUD stays visible.",
  "app.hudAlert.cancel": "Cancel",
  "app.hudAlert.confirm": "Switch to HUD",
  "app.hudAlert.exclusive": "Exclusive fullscreen",
  "app.hudAlert.exclusiveNote": "Bypasses the desktop, so the HUD is not visible there.",
  "app.hudAlert.intro": "The overlay stays on top of windowed apps and games.",
  "app.hudAlert.mute": "Don't show this again",
  "app.hudAlert.title": "HUD overlay",
  "app.hudAlert.videoSetting": "Windowed Fullscreen (Borderless)",
  "app.recording": "Recording",
  "app.splash.starting": "starting sensors…",
  "app.stress.running": "Stress test running",
  "app.tab.about": "About",
  "app.tab.monitor": "Monitor",
  "app.tab.processes": "Processes",
  "app.tab.sessions": "Sessions",
  "app.tab.settings": "Settings",
  "app.tab.stress": "Stress test",
  "app.theme.toggle": "Toggle light / dark theme",
  "app.theme.toggleAria": "Toggle theme",
  "app.update.available": "Update available",
  "app.window.close": "Close",
  "app.window.maximise": "Maximise",
  "app.window.minimise": "Minimise",
  "dash.collecting": "Collecting first samples…",
  "dash.health.bad": "Unhealthy",
  "dash.health.ok": "Healthy",
  "dash.health.warning": "Warning",
  "dash.range.15m": "15m",
  "dash.range.1m": "1m",
  "dash.range.30m": "30m",
  "dash.range.5m": "5m",
  "dash.rec.autostop": "auto-stop {n} min",
  "dash.rec.name.placeholder": "Session name (optional)",
  "dash.rec.start": "Record",
  "dash.rec.stop": "Stop",
  "dash.sys.admin": "administrator",
  "dash.sys.board": "Motherboard",
  "dash.sys.cpu": "Processor",
  "dash.sys.cpu.base": "base {v} GHz",
  "dash.sys.cpu.cores": "{n} cores",
  "dash.sys.cpu.threads": "{n} threads",
  "dash.sys.drive": "Drive",
  "dash.sys.gpu": "Graphics",
  "dash.sys.gpu.none": "Not detected",
  "dash.sys.gpu.vram": "{n} GB VRAM",
  "dash.sys.os": "System",
  "dash.sys.ram": "Memory",
  "dash.sys.standard": "standard privileges",
  "dash.sys.unknown": "Unknown",
  "dash.sys.uptime.dh": "up {d} d {h} h",
  "dash.sys.uptime.hm": "up {h} h {m} min",
  "dash.tile.disk": "Disk",
  "dash.tile.disk.sub": "Read / Write · MB/s",
  "dash.tile.net": "Net",
  "dash.tile.nodata": "no data",
  "dash.tile.ram.sub": "{pct}% of {total} GB",
  "dash.tile.vram.sub": "of {total} GB",
  "m.chart.cpu-load": "CPU load",
  "m.chart.disk-io": "Disk I/O",
  "m.chart.fps": "FPS (foreground app)",
  "m.chart.gpu-load": "GPU load",
  "m.chart.network": "Network",
  "m.chart.page-file": "Page file (swap)",
  "m.chart.power-draw": "Power draw",
  "m.chart.ram-used": "RAM used",
  "m.chart.temperature": "Temperature",
  "m.chart.vram-used": "VRAM used",
  "m.group.cpu": "CPU",
  "m.group.fps": "FPS",
  "m.group.gpu": "GPU",
  "m.group.net": "Network",
  "m.group.ram": "Memory",
  "m.group.storage": "Storage",
  "m.row.clock": "Core clock",
  "m.row.down": "Download",
  "m.row.fan": "Fan",
  "m.row.fps.avg": "Average",
  "m.row.fps.cur": "In-time",
  "m.row.fps.graph": "FPS graph",
  "m.row.fps.low01": "0.1% low",
  "m.row.fps.low1": "1% low",
  "m.row.frametime.graph": "Frame time graph",
  "m.row.hotspot": "Hot spot",
  "m.row.load": "Load",
  "m.row.memclock": "Memory clock",
  "m.row.power": "Power",
  "m.row.ramspeed": "Speed",
  "m.row.read": "Read",
  "m.row.temp": "Temperature",
  "m.row.up": "Upload",
  "m.row.used": "Used",
  "m.row.vram": "VRAM",
  "m.row.write": "Write",
  "m.series.cpu": "CPU",
  "m.series.down": "Down",
  "m.series.fps": "FPS",
  "m.series.gpu": "GPU",
  "m.series.read": "Read",
  "m.series.size": "Size",
  "m.series.up": "Up",
  "m.series.used": "Used",
  "m.series.write": "Write",
  "misc.about.check": "Check for updates",
  "misc.about.openSource": "open source",
  "misc.about.phase.available": "{ver} is available —",
  "misc.about.phase.checking": "checking…",
  "misc.about.phase.downloading": "downloading and swapping the executable…",
  "misc.about.phase.idle": "checked automatically once a day",
  "misc.about.phase.ready": "installed — restart to finish",
  "misc.about.phase.uptodate": "v{ver} is the latest version",
  "misc.about.releaseNotes": "release notes",
  "misc.about.restart": "Restart now",
  "misc.about.star": "Star on GitHub",
  "misc.about.starHint": "Open the repository and star it",
  "misc.about.updateTo": "Update to {ver}",
  "misc.about.updates": "Updates",
  "misc.export.interval": "every {n} ms",
  "misc.export.samples": {"one":"{count} sample","other":"{count} samples"},
  "misc.proc.col.cpu": "CPU %",
  "misc.proc.col.io": "I/O",
  "misc.proc.col.mem": "Memory",
  "misc.proc.col.name": "Process",
  "misc.proc.col.threads": "Threads",
  "misc.proc.count": {"one":"{n} process","other":"{n} processes"},
  "misc.proc.filter": "Filter by name or pid",
  "misc.proc.group": "Group by name",
  "misc.proc.loading": "Reading the process table…",
  "misc.proc.noMatch": "Nothing matches “{query}”",
  "misc.proc.note.cpu": "CPU is the share of the whole machine, the way Task Manager counts it — a process using every core reads 100 %.",
  "misc.proc.note.io": "is every read and write the process made, including the ones the file cache served without touching a drive, so it is higher than the disk activity on the Monitor tab.",
  "misc.proc.private": "{size} private commit",
  "misc.proc.running": "{n} running",
  "misc.proc.rw": "read {read} · write {write}",
  "misc.proc.showAll": "Show all {count} rows",
  "misc.proc.showTop": "Show top {n}",
  "misc.proc.stale": "table not refreshing",
  "misc.proc.threads": {"one":"{count} thread","other":"{count} threads"},
  "misc.proc.title": "Processes",
  "misc.proc.waiting": "Waiting for the first enumeration…",
  "sess.back": "Back",
  "sess.delete": "Delete",
  "sess.deleteConfirm": "Sure?",
  "sess.dur.hourMin": "{h} h {m} min",
  "sess.dur.minSec": "{m} min {s} s",
  "sess.dur.recording": "recording…",
  "sess.empty": "No recordings yet. Start one with the Record button on the Monitor tab — it captures every metric for up to 4 hours.",
  "sess.exportPng": "Export PNG",
  "sess.interval": "every {ms} ms",
  "sess.loading": "Loading…",
  "sess.open": "Open",
  "sess.rendering": "Rendering…",
  "sess.samples": {"one":"{count} sample","other":"{count} samples"},
  "sess.savedTo": "Saved to {path}",
  "sess.storage.drives": "Drives · SMART",
  "sess.storage.life": "Remaining life",
  "sess.storage.needAdmin": "run as admin for temp/wear",
  "sess.storage.noDrives": "No drive info available",
  "sess.storage.poweredOn": "{n} h powered on",
  "sess.storage.read": "Read",
  "sess.storage.smartTip": "SMART pass-through needs elevation",
  "sess.storage.usedPercent": "{p}% used",
  "sess.storage.volumes": "Volumes · live I/O",
  "sess.storage.waiting": "Waiting for samples…",
  "sess.storage.write": "Write",
  "sess.title": "Recorded sessions",
  "sess.zoomHint": "drag to zoom · double-click to reset",
  "settings.alerts.about": "A Windows notification and an in-app toast when a value crosses its limit. Each alert fires once per incident and re-arms after the value settles; set a limit to 0 to switch that rule off.",
  "settings.alerts.cpuTemp": "CPU temperature",
  "settings.alerts.diskFill": "Drive fill level",
  "settings.alerts.gpuTemp": "GPU temperature",
  "settings.alerts.ramUsage": "RAM usage",
  "settings.alerts.title": "Alerts",
  "settings.driver.installed": "installed",
  "settings.driver.label": "Sensor driver —",
  "settings.hud.about.anchorPost": "it is draggable and its position is remembered; on a corner it stays pinned there.",
  "settings.hud.about.anchorPre": "On",
  "settings.hud.about.clickThrough": "A click-through overlay cannot be clicked or dragged — use its shortcut to make it interactive again.",
  "settings.hud.about.fullscreen": "It stays above windowed and borderless-fullscreen games (exclusive fullscreen hides any overlay).",
  "settings.hud.about.shortcuts": "The shortcuts work while a game has focus: click one and press the combination you want. Windows gives a combination to whichever application asks for it first, so if one is reported as held elsewhere, pick another.",
  "settings.hud.about.size": "The HUD is a compact always-on-top overlay. Its height follows the metrics you enable below — the window cannot be resized by hand.",
  "settings.hud.anchor.bl": "↙ Bottom left",
  "settings.hud.anchor.br": "↘ Bottom right",
  "settings.hud.anchor.free": "Free (drag)",
  "settings.hud.anchor.freeName": "Free",
  "settings.hud.anchor.tl": "↖ Top left",
  "settings.hud.anchor.tr": "↗ Top right",
  "settings.hud.clickThrough": "Click-through",
  "settings.hud.clickThrough.hint": "Mouse clicks pass through the overlay into the game",
  "settings.hud.hotkeyClickThrough": "Toggle click-through",
  "settings.hud.hotkeyReset": "Restart average and lows",
  "settings.hud.hotkeyToggle": "Show / hide the overlay",
  "settings.hud.opacity": "Background opacity",
  "settings.hud.position": "Screen position",
  "settings.hud.shortcuts": "Shortcuts",
  "settings.hud.title": "HUD overlay",
  "settings.hud.width": "Width",
  "settings.hudRows.title": "HUD sections and rows",
  "settings.interval.ms": "{n} ms",
  "settings.interval.s": "{n} s",
  "settings.lang.auto": "Match Windows",
  "settings.lang.label": "Interface language",
  "settings.recording.autoStop": "Recording auto-stop",
  "settings.recording.hours": {"one":"{n} hour","other":"{n} hours"},
  "settings.retention.days": {"one":"{n} day","other":"{n} days"},
  "settings.retention.forever": "Keep forever",
  "settings.retention.label": "Delete recordings older than",
  "settings.retention.year1": "1 year",
  "settings.sampling.interval": "Sampling interval",
  "settings.sampling.title": "Sampling & recording",
  "settings.save": "Save changes",
  "settings.saved": "Saved ✓",
  "settings.sources.fps": "Frame capture (PresentMon)",
  "settings.sources.running": "running",
  "settings.sources.sensors": "Hardware sensors",
  "settings.sources.stopped": "not running",
  "settings.system.title": "System",
  "settings.title": "Settings",
  "settings.uiScale.auto": "Match Windows",
  "settings.uiScale.current": "now {n}%",
  "settings.uiScale.label": "Interface scale",
  "settings.unsaved": "unsaved changes",
  "settings.updateCheck": "Check for updates daily",
  "stress.cpu.avx512": "Use AVX-512 where present",
  "stress.cpu.threads": "Threads",
  "stress.disk.drive": "Drive",
  "stress.disk.file": "Test file",
  "stress.disk.tempFolder": "Temp folder",
  "stress.duration.10m": "10 min",
  "stress.duration.1h": "1 hour",
  "stress.duration.1m": "1 min",
  "stress.duration.30m": "30 min",
  "stress.duration.5m": "5 min",
  "stress.duration.custom": "Custom",
  "stress.duration.minutes": "min",
  "stress.duration.untilStopped": "— until stopped",
  "stress.faults.count": {"one":"{n} data mismatch — this memory is not stable under load","other":"{n} data mismatches — this memory is not stable under load"},
  "stress.faults.none": "No data mismatches",
  "stress.gpu.share": "Share of VRAM",
  "stress.node.cpu.blurb": "Rotates every thread through wide FMA (AVX-512 or AVX2), AES-NI, the SHA extensions, a 1024-bit modular exponentiation, a random cache walk and the transcendental library, so no execution port is left idle.",
  "stress.node.cpu.title": "Processor",
  "stress.node.disk.blurb": "Writes an unbuffered test file to bypass the cache, then alternates large sequential transfers with 4 KB random requests at queue depth 16. The file is deleted when the run ends.",
  "stress.node.disk.subtitle": "Sequential and random I/O",
  "stress.node.disk.title": "Storage",
  "stress.node.gpu.blurb": "Runs an OpenCL compute kernel on the shader array, fills VRAM to the chosen share and streams all of it through the memory interface — the part that an unstable memory clock trips over — verifying the contents on every pass.",
  "stress.node.gpu.title": "Graphics",
  "stress.node.ram.blurb": "Claims the free memory, writes an address-derived checkerboard pattern, streams the whole region through the controller and verifies it twice per pass. Mismatches are counted as faults.",
  "stress.node.ram.subtitle": "System memory",
  "stress.node.ram.title": "Memory",
  "stress.peak.cpuClock": "CPU clock",
  "stress.peak.cpuLoad": "CPU load",
  "stress.peak.cpuPow": "CPU power",
  "stress.peak.cpuTemp": "CPU temp",
  "stress.peak.gpuClock": "GPU clock",
  "stress.peak.gpuFan": "GPU fan",
  "stress.peak.gpuHotspot": "GPU hot spot",
  "stress.peak.gpuLoad": "GPU load",
  "stress.peak.gpuMemClock": "GPU mem clock",
  "stress.peak.gpuPow": "GPU power",
  "stress.peak.gpuTemp": "GPU temp",
  "stress.peak.ram": "RAM used",
  "stress.peaks.title": "Peaks during this run",
  "stress.ram.share": "Share of free memory",
  "stress.runSelected": "Run selected",
  "stress.select": "select",
  "stress.selectHint": "Include in “Run selected”",
  "stress.start": "Start",
  "stress.state.done": "done",
  "stress.state.failed": "failed",
  "stress.state.running": "running",
  "stress.state.starting": "starting",
  "stress.state.stopped": "stopped",
  "stress.stop": "Stop",
  "stress.stopAll": "Stop all",
  "stress.timeLeft": "{time} left",
  "stress.title": "Stress test",
  "stress.warning.body": "— a stress test drives the machine well past any normal workload: expect maximum fan noise, a hot case and full power draw. Stop the run if temperatures keep climbing, and be aware that the storage test writes several gigabytes per round, which counts against an SSD's endurance.",
  "stress.warning.label": "Warning",
}
