// Russian catalogue. Same keys as lang.en.js; anything missing falls back to
// the English string rather than to the key, so a gap reads as an untranslated
// app rather than a broken one.
export default {
  "alert.cpuTemp": "Температура CPU {value} °C — предел {limit} °C",
  "alert.disk": "Накопитель {name} заполнен на {value}% — предел {limit}%",
  "alert.gpuTemp": "Температура GPU {value} °C — предел {limit} °C",
  "alert.ram": "Загрузка RAM {value}% — предел {limit}%",
  "app.alert.dismiss": "Закрыть оповещение",
  "app.alert.label": "Оповещение",
  "app.gate.afterLink": "— открытый драйвер режима ядра, который устанавливается один раз на всю систему. Без него приложение не запустится. Установка выполняется через winget из официального пакета; само приложение ничего не скачивает.",
  "app.gate.beforeLink": "Open Monitoring читает датчики оборудования через",
  "app.gate.check": "Проверить снова",
  "app.gate.checking": "Проверка…",
  "app.gate.install": "Установить PawnIO",
  "app.gate.installing": "Установка…",
  "app.gate.subtitle": "требуется драйвер",
  "app.hotkey.listening": "нажмите клавиши…",
  "app.hotkey.taken": "занято другим приложением",
  "app.hud.clickThrough": "Сквозные клики: мышь проходит в игру",
  "app.hud.enter": "Перейти в HUD",
  "app.hud.exit": "Вернуться в приложение",
  "app.hudAlert.advice": "В настройках графики выберите режим",
  "app.hudAlert.borderless": "Полноэкранный оконный",
  "app.hudAlert.borderlessNote": "HUD остаётся виден.",
  "app.hudAlert.cancel": "Отмена",
  "app.hudAlert.confirm": "Перейти в HUD",
  "app.hudAlert.exclusive": "Эксклюзивный полноэкранный",
  "app.hudAlert.exclusiveNote": "Игра выводится мимо рабочего стола, поэтому HUD в ней не виден.",
  "app.hudAlert.intro": "Оверлей отображается поверх приложений и игр в оконном режиме.",
  "app.hudAlert.mute": "Больше не показывать",
  "app.hudAlert.title": "Оверлей HUD",
  "app.hudAlert.videoSetting": "Полноэкранный оконный (без рамки)",
  "app.recording": "Идёт запись сеанса",
  "app.splash.starting": "запуск датчиков…",
  "app.stress.running": "Выполняется стресс-тест",
  "app.tab.about": "О программе",
  "app.tab.monitor": "Монитор",
  "app.tab.processes": "Процессы",
  "app.tab.sessions": "Сеансы",
  "app.tab.settings": "Настройки",
  "app.tab.stress": "Стресс-тест",
  "app.theme.toggle": "Светлая / тёмная тема",
  "app.theme.toggleAria": "Переключить тему",
  "app.update.available": "Доступно обновление",
  "app.window.close": "Закрыть",
  "app.window.maximise": "Развернуть",
  "app.window.minimise": "Свернуть",
  "dash.collecting": "Сбор первых замеров…",
  "dash.health.bad": "Неисправен",
  "dash.health.ok": "Исправен",
  "dash.health.warning": "Внимание",
  "dash.range.15m": "15 мин",
  "dash.range.1m": "1 мин",
  "dash.range.30m": "30 мин",
  "dash.range.5m": "5 мин",
  "dash.rec.autostop": "остановка через {n} мин",
  "dash.rec.name.placeholder": "Имя сеанса (необязательно)",
  "dash.rec.start": "Начать запись",
  "dash.rec.stop": "Стоп",
  "dash.sys.admin": "администратор",
  "dash.sys.board": "Системная плата",
  "dash.sys.cpu": "Процессор",
  "dash.sys.cpu.base": "база {v} GHz",
  "dash.sys.cpu.cores": {"one":"{n} ядро","few":"{n} ядра","many":"{n} ядер","other":"{n} ядра"},
  "dash.sys.cpu.threads": {"one":"{n} поток","few":"{n} потока","many":"{n} потоков","other":"{n} потока"},
  "dash.sys.drive": "Накопитель",
  "dash.sys.gpu": "Видеокарта",
  "dash.sys.gpu.none": "Не обнаружена",
  "dash.sys.gpu.vram": "{n} GB VRAM",
  "dash.sys.os": "Система",
  "dash.sys.ram": "Память",
  "dash.sys.standard": "обычный пользователь",
  "dash.sys.unknown": "Неизвестно",
  "dash.sys.uptime.dh": "{d} д {h} ч",
  "dash.sys.uptime.hm": "{h} ч {m} мин",
  "dash.tile.disk": "Диск",
  "dash.tile.disk.sub": "Чт. / Зап. · MB/s",
  "dash.tile.net": "Сеть",
  "dash.tile.nodata": "нет данных",
  "dash.tile.ram.sub": "{pct}% из {total} GB",
  "dash.tile.vram.sub": "из {total} GB",
  "m.chart.cpu-load": "Загрузка CPU",
  "m.chart.disk-io": "Диск · I/O",
  "m.chart.fps": "FPS (активное приложение)",
  "m.chart.gpu-load": "Загрузка GPU",
  "m.chart.network": "Сеть",
  "m.chart.page-file": "Файл подкачки",
  "m.chart.power-draw": "Потребление",
  "m.chart.ram-used": "Занято RAM",
  "m.chart.temperature": "Температура",
  "m.chart.vram-used": "Занято VRAM",
  "m.group.cpu": "CPU",
  "m.group.fps": "FPS",
  "m.group.gpu": "GPU",
  "m.group.net": "Сеть",
  "m.group.ram": "Память",
  "m.group.storage": "Накопители",
  "m.row.clock": "Частота",
  "m.row.down": "Приём",
  "m.row.fan": "Вентилятор",
  "m.row.fps.avg": "Средний",
  "m.row.fps.cur": "Текущий",
  "m.row.fps.graph": "График FPS",
  "m.row.fps.low01": "0.1% Low",
  "m.row.fps.low1": "1% Low",
  "m.row.frametime.graph": "График времени кадра",
  "m.row.hotspot": "Горячая точка",
  "m.row.load": "Загрузка",
  "m.row.memclock": "Частота памяти",
  "m.row.power": "Потребление",
  "m.row.ramspeed": "Частота",
  "m.row.read": "Чтение",
  "m.row.temp": "Температура",
  "m.row.up": "Передача",
  "m.row.used": "Занято",
  "m.row.vram": "VRAM",
  "m.row.write": "Запись",
  "m.series.cpu": "CPU",
  "m.series.down": "Приём",
  "m.series.fps": "FPS",
  "m.series.gpu": "GPU",
  "m.series.read": "Чтение",
  "m.series.size": "Размер",
  "m.series.up": "Передача",
  "m.series.used": "Занято",
  "m.series.write": "Запись",
  "misc.about.check": "Проверить обновления",
  "misc.about.openSource": "открытый код",
  "misc.about.phase.available": "доступна {ver} —",
  "misc.about.phase.checking": "проверка…",
  "misc.about.phase.downloading": "загрузка и замена исполняемого файла…",
  "misc.about.phase.idle": "проверяется автоматически раз в сутки",
  "misc.about.phase.ready": "обновление установлено — нужен перезапуск",
  "misc.about.phase.uptodate": "v{ver} — последняя версия",
  "misc.about.releaseNotes": "примечания к выпуску",
  "misc.about.restart": "Перезапустить",
  "misc.about.star": "Поставить звезду",
  "misc.about.starHint": "Открыть репозиторий и поставить звезду",
  "misc.about.updateTo": "Обновить до {ver}",
  "misc.about.updates": "Обновления",
  "misc.export.interval": "интервал {n} мс",
  "misc.export.samples": {"one":"{count} замер","few":"{count} замера","many":"{count} замеров","other":"{count} замера"},
  "misc.proc.col.cpu": "CPU %",
  "misc.proc.col.io": "I/O",
  "misc.proc.col.mem": "Память",
  "misc.proc.col.name": "Процесс",
  "misc.proc.col.threads": "Потоки",
  "misc.proc.count": {"one":"{n} процесс","few":"{n} процесса","many":"{n} процессов","other":"{n} процесса"},
  "misc.proc.filter": "Фильтр по имени или pid",
  "misc.proc.group": "Группировать по имени",
  "misc.proc.loading": "Чтение таблицы процессов…",
  "misc.proc.noMatch": "Нет совпадений с «{query}»",
  "misc.proc.note.cpu": "CPU считается от всей машины, как в Диспетчере задач: процесс, занявший все ядра, показывает 100 %.",
  "misc.proc.note.io": "— это все операции чтения и записи процесса, включая те, что обслужил файловый кэш без обращения к накопителю, поэтому значение выше, чем активность диска на вкладке «Монитор».",
  "misc.proc.private": "{size} выделенной памяти",
  "misc.proc.running": "запущено {n}",
  "misc.proc.rw": "чтение {read} · запись {write}",
  "misc.proc.showAll": "Показать все строки ({count})",
  "misc.proc.showTop": "Показать первые {n}",
  "misc.proc.stale": "таблица не обновляется",
  "misc.proc.threads": {"one":"{count} поток","few":"{count} потока","many":"{count} потоков","other":"{count} потока"},
  "misc.proc.title": "Процессы",
  "misc.proc.waiting": "Ожидание первого опроса…",
  "sess.back": "Назад",
  "sess.delete": "Удалить",
  "sess.deleteConfirm": "Точно?",
  "sess.dur.hourMin": "{h} ч {m} мин",
  "sess.dur.minSec": "{m} мин {s} с",
  "sess.dur.recording": "идёт запись…",
  "sess.empty": "Записей пока нет. Начните первую кнопкой «Начать запись» на вкладке «Монитор» — она сохраняет все метрики до 4 часов подряд.",
  "sess.exportPng": "Экспорт PNG",
  "sess.interval": "интервал {ms} мс",
  "sess.loading": "Загрузка…",
  "sess.open": "Открыть",
  "sess.rendering": "Отрисовка…",
  "sess.samples": {"one":"{count} замер","few":"{count} замера","many":"{count} замеров","other":"{count} замера"},
  "sess.savedTo": "Сохранено: {path}",
  "sess.storage.drives": "Накопители · SMART",
  "sess.storage.life": "Остаточный ресурс",
  "sess.storage.needAdmin": "нужны права администратора",
  "sess.storage.noDrives": "Нет данных о накопителях",
  "sess.storage.poweredOn": "{n} ч наработки",
  "sess.storage.read": "Чтение",
  "sess.storage.smartTip": "Чтение SMART требует прав администратора",
  "sess.storage.usedPercent": "занято {p}%",
  "sess.storage.volumes": "Тома · текущий I/O",
  "sess.storage.waiting": "Ожидание замеров…",
  "sess.storage.write": "Запись",
  "sess.title": "Записанные сеансы",
  "sess.zoomHint": "выделите область — увеличить · двойной клик — сбросить",
  "settings.alerts.about": "Когда значение выходит за порог, приходит уведомление Windows и всплывающее сообщение в приложении. Оповещение срабатывает один раз за событие и взводится заново, когда значение возвращается в норму. Чтобы отключить правило, задайте порог 0.",
  "settings.alerts.cpuTemp": "Температура CPU",
  "settings.alerts.diskFill": "Заполнение диска",
  "settings.alerts.gpuTemp": "Температура GPU",
  "settings.alerts.ramUsage": "Заполнение RAM",
  "settings.alerts.title": "Оповещения",
  "settings.driver.installed": "установлен",
  "settings.driver.label": "Драйвер датчиков —",
  "settings.hud.about.anchorPost": "позволяет перетаскивать оверлей мышью, и его положение запоминается; при выборе угла он закрепляется там.",
  "settings.hud.about.anchorPre": "Режим",
  "settings.hud.about.clickThrough": "Оверлей со сквозными кликами нельзя ни щёлкнуть, ни перетащить — вернуть его в обычный режим можно только горячей клавишей.",
  "settings.hud.about.fullscreen": "Оверлей виден поверх игр в окне и в полноэкранном оконном режиме; эксклюзивный полноэкранный режим скрывает любой оверлей.",
  "settings.hud.about.shortcuts": "Горячие клавиши работают, пока активна игра: щёлкните по полю и нажмите нужное сочетание. Windows отдаёт сочетание тому приложению, которое запросило его первым, поэтому, если сочетание уже занято, выберите другое.",
  "settings.hud.about.size": "HUD — компактный оверлей поверх всех окон. Его высота подстраивается под выбранные ниже строки; вручную размер изменить нельзя.",
  "settings.hud.anchor.bl": "↙ Внизу слева",
  "settings.hud.anchor.br": "↘ Внизу справа",
  "settings.hud.anchor.free": "Свободно",
  "settings.hud.anchor.freeName": "Свободно",
  "settings.hud.anchor.tl": "↖ Вверху слева",
  "settings.hud.anchor.tr": "↗ Вверху справа",
  "settings.hud.clickThrough": "Сквозные клики",
  "settings.hud.clickThrough.hint": "Клики мыши проходят сквозь оверлей в игру",
  "settings.hud.hotkeyClickThrough": "Переключить сквозные клики",
  "settings.hud.hotkeyReset": "Сбросить средний FPS и минимумы",
  "settings.hud.hotkeyToggle": "Показать / скрыть оверлей",
  "settings.hud.opacity": "Непрозрачность фона",
  "settings.hud.position": "Положение на экране",
  "settings.hud.shortcuts": "Горячие клавиши",
  "settings.hud.title": "Оверлей HUD",
  "settings.hud.width": "Ширина",
  "settings.hudRows.title": "Разделы и строки HUD",
  "settings.interval.ms": "{n} мс",
  "settings.interval.s": "{n} с",
  "settings.lang.auto": "Как в Windows",
  "settings.lang.label": "Язык интерфейса",
  "settings.recording.autoStop": "Останавливать запись через",
  "settings.recording.hours": {"one":"{n} час","few":"{n} часа","many":"{n} часов","other":"{n} часа"},
  "settings.retention.days": {"one":"{n} день","few":"{n} дня","many":"{n} дней","other":"{n} дня"},
  "settings.retention.forever": "Всегда",
  "settings.retention.label": "Хранить записи",
  "settings.retention.year1": "1 год",
  "settings.sampling.interval": "Интервал опроса",
  "settings.sampling.title": "Опрос и запись",
  "settings.save": "Сохранить",
  "settings.saved": "Сохранено ✓",
  "settings.sources.fps": "Захват кадров (PresentMon)",
  "settings.sources.running": "работает",
  "settings.sources.sensors": "Датчики оборудования",
  "settings.sources.stopped": "не работает",
  "settings.system.title": "Система",
  "settings.title": "Настройки",
  "settings.uiScale.auto": "Как в Windows",
  "settings.uiScale.current": "сейчас {n}%",
  "settings.uiScale.label": "Масштаб интерфейса",
  "settings.unsaved": "несохранённые изменения",
  "settings.updateCheck": "Ежедневно проверять обновления",
  "stress.cpu.avx512": "Использовать AVX-512, если доступен",
  "stress.cpu.threads": "Потоки",
  "stress.disk.drive": "Диск",
  "stress.disk.file": "Тестовый файл",
  "stress.disk.tempFolder": "Временная папка",
  "stress.duration.10m": "10 мин",
  "stress.duration.1h": "1 ч",
  "stress.duration.1m": "1 мин",
  "stress.duration.30m": "30 мин",
  "stress.duration.5m": "5 мин",
  "stress.duration.custom": "Другое",
  "stress.duration.minutes": "мин",
  "stress.duration.untilStopped": "— до остановки",
  "stress.faults.count": {"one":"{n} несовпадение данных — память нестабильна под нагрузкой","few":"{n} несовпадения данных — память нестабильна под нагрузкой","many":"{n} несовпадений данных — память нестабильна под нагрузкой","other":"{n} несовпадения данных — память нестабильна под нагрузкой"},
  "stress.faults.none": "Несовпадений данных нет",
  "stress.gpu.share": "Доля VRAM",
  "stress.node.cpu.blurb": "Прогоняет каждый поток через широкие FMA-инструкции (AVX-512 или AVX2), AES-NI, инструкции SHA, 1024-битное возведение в степень по модулю, случайные обращения по всему кэшу и библиотеку трансцендентных функций — так, чтобы ни один исполнительный порт не простаивал.",
  "stress.node.cpu.title": "Процессор",
  "stress.node.disk.blurb": "Записывает тестовый файл без буферизации, мимо кэша, а затем чередует крупные последовательные операции со случайными запросами по 4 KB при глубине очереди 16. По завершении прогона файл удаляется.",
  "stress.node.disk.subtitle": "Последовательный и случайный доступ",
  "stress.node.disk.title": "Накопитель",
  "stress.node.gpu.blurb": "Запускает вычислительное ядро OpenCL на шейдерных блоках, заполняет заданную долю VRAM и прогоняет весь этот объём через шину памяти — именно здесь проявляется нестабильность частоты памяти, — сверяя содержимое на каждом проходе.",
  "stress.node.gpu.title": "Видеокарта",
  "stress.node.ram.blurb": "Занимает свободную память, записывает в неё шахматный узор, вычисляемый из адреса, прогоняет весь массив через контроллер памяти и дважды за проход сверяет содержимое. Каждое несовпадение считается ошибкой.",
  "stress.node.ram.subtitle": "Системная память",
  "stress.node.ram.title": "Память",
  "stress.peak.cpuClock": "Частота CPU",
  "stress.peak.cpuLoad": "Загрузка CPU",
  "stress.peak.cpuPow": "Потребление CPU",
  "stress.peak.cpuTemp": "Температура CPU",
  "stress.peak.gpuClock": "Частота GPU",
  "stress.peak.gpuFan": "Вентилятор GPU",
  "stress.peak.gpuHotspot": "Горячая точка GPU",
  "stress.peak.gpuLoad": "Загрузка GPU",
  "stress.peak.gpuMemClock": "Частота памяти GPU",
  "stress.peak.gpuPow": "Потребление GPU",
  "stress.peak.gpuTemp": "Температура GPU",
  "stress.peak.ram": "Занято RAM",
  "stress.peaks.title": "Пики за прогон",
  "stress.ram.share": "Доля свободной памяти",
  "stress.runSelected": "Запустить выбранные",
  "stress.select": "выбрать",
  "stress.selectHint": "Включить в «Запустить выбранные»",
  "stress.start": "Старт",
  "stress.state.done": "завершён",
  "stress.state.failed": "сбой",
  "stress.state.running": "работает",
  "stress.state.starting": "запуск",
  "stress.state.stopped": "остановлен",
  "stress.stop": "Стоп",
  "stress.stopAll": "Остановить всё",
  "stress.timeLeft": "осталось {time}",
  "stress.title": "Стресс-тест",
  "stress.warning.body": "— стресс-тест нагружает систему намного сильнее любой обычной задачи: вентиляторы выйдут на максимум, корпус нагреется, энергопотребление достигнет предела. Если температура продолжает расти, остановите прогон. Учтите также, что тест накопителя пишет несколько гигабайт за проход, а это расходует ресурс SSD.",
  "stress.warning.label": "Внимание",
}
